In [1]:
import numpy as np
streetlights = np.array([[1, 0, 1],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1],
                         [0, 1, 1],
                         [1, 0, 1]])
walk_vs_stop = np.array([[0],
                         [1],
                         [0],
                         [1],
                         [1],
                         [0]])

In [2]:
def single():
    weights = np.array([0.5, 0.48, -0.7])
    alpha = 0.1
    input = streetlights[0]
    goal_prediction = walk_vs_stop[0]
    for iteration in range(20):
        prediction = input.dot(weights)
        error = (goal_prediction - prediction) ** 2
        delta = prediction - goal_prediction
        weights = weights - (alpha * (input * delta))

        print(f"Error: {error}, Prediction {prediction}")
single()

Error: [0.04], Prediction -0.19999999999999996
Error: [0.0256], Prediction -0.15999999999999992
Error: [0.016384], Prediction -0.1279999999999999
Error: [0.01048576], Prediction -0.10239999999999982
Error: [0.00671089], Prediction -0.08191999999999977
Error: [0.00429497], Prediction -0.06553599999999982
Error: [0.00274878], Prediction -0.05242879999999994
Error: [0.00175922], Prediction -0.04194304000000004
Error: [0.0011259], Prediction -0.03355443200000008
Error: [0.00072058], Prediction -0.02684354560000002
Error: [0.00046117], Prediction -0.021474836479999926
Error: [0.00029515], Prediction -0.01717986918399994
Error: [0.00018889], Prediction -0.013743895347199997
Error: [0.00012089], Prediction -0.010995116277759953
Error: [7.73712525e-05], Prediction -0.008796093022207963
Error: [4.95176016e-05], Prediction -0.007036874417766459
Error: [3.1691265e-05], Prediction -0.0056294995342132115
Error: [2.02824096e-05], Prediction -0.004503599627370569
Error: [1.29807421e-05], Prediction -

In [5]:
def sgd():
    weights = np.array([0.5, 0.48, -0.7])
    alpha = 0.1
    for iteration in range(40):
        error_for_all_lights = 0
        for row_index in range(len(walk_vs_stop)):
            input = streetlights[row_index]
            goal_prediction = walk_vs_stop[row_index]

            prediction = input.dot(weights)

            error = (goal_prediction - prediction) ** 2
            error_for_all_lights += error

            delta = prediction - goal_prediction
            weights = weights - (alpha * (input * delta))
            print(f"Prediction: {prediction}")
        print(weights)
        print(f"Error: {error_for_all_lights}")
sgd()

Prediction: -0.19999999999999996
Prediction: -0.19999999999999996
Prediction: -0.5599999999999999
Prediction: 0.6160000000000001
Prediction: 0.17279999999999995
Prediction: 0.17552
[ 0.540848  0.72112  -0.400432]
Error: [2.65612311]
Prediction: 0.14041599999999999
Prediction: 0.3066464
Prediction: -0.34513824
Prediction: 1.006637344
Prediction: 0.4785034751999999
Prediction: 0.26700416768
[ 0.49944225  0.84194128 -0.28583891]
Error: [0.96287018]
Prediction: 0.213603334144
Prediction: 0.5347420299776
Prediction: -0.26067345110016
Prediction: 1.1319428845096962
Prediction: 0.6274723921901568
Prediction: 0.25433999330650114
[ 0.43945363  0.91252555 -0.23598163]
Error: [0.55091659]
Prediction: 0.20347199464520088
Prediction: 0.6561967149569552
Prediction: -0.221948503950995
Prediction: 1.166258650532124
Prediction: 0.7139004922542389
Prediction: 0.21471099528371604
[ 0.38100946  0.95888996 -0.20924067]
Error: [0.36445837]
Prediction: 0.17176879622697283
Prediction: 0.7324724146523222
Predi

In [8]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

alpha = 0.2
hidden_size = 4

streetlights = np.array([[1, 0, 1],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1]])

walk_vs_stop = np.array([[1, 1, 0, 0]]).T

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

layer_0 = streetlights[0]
layer_1 = relu(np.dot(layer_0, weights_0_1))
layer_2 = np.dot(layer_1, weights_1_2)

In [19]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

alpha = 0.2
hidden_size = 4

streetlights = np.array([[1, 0, 1],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1]])

walk_vs_stop = np.array([[1, 1, 0, 0]]).T

def simple_dnn():
    weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
    weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1
    for iteration in range(60):
        layer_2_error = 0
        for i in range(len(streetlights)):
            layer_0 = streetlights[i:i+1]
            layer_1 = relu(np.dot(layer_0, weights_0_1))
            layer_2 = np.dot(layer_1, weights_1_2)
            layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
            
            layer_2_delta = (walk_vs_stop[i:i+1] - layer_2)
            layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
            
            weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
            weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
            
        if(iteration % 10 == 9):
            print(f"Error: {layer_2_error}")
simple_dnn()

Error: 0.6342311598444467
Error: 0.35838407676317513
Error: 0.0830183113303298
Error: 0.006467054957103705
Error: 0.0003292669000750734
Error: 1.5055622665134859e-05
